export * from './creative-commons/creativecommons.component'
export * from './about/about.component'
export * from './privacy/privacy.component'
export * from './support-us/support-us.component'
export * from './editors/editors.component'