export * from './article-detail/article-detail.component';
export * from './articles/articles.component';
export * from './dashboard/dashboard.component'
export * from './page-not-found/page-not-found.component'
export * from './send-translation/send-translation.component'
export * from './main-page/main-page.component'
export * from './published-article-detail/published-article-detail.component'
export * from './login/login.component'
export * from './cat-lyrics/cat-lyrics.component'
export * from './cat-poems/cat-poems.component'
export * from './cat-prose/cat-prose.component'